#parameters:
#    mangocelecore.example.class: Mangocele\coreBundle\Example

services:
    my.custom.service.id:
        class: Mangocele\coreBundle\Services\UserService
        arguments: [ @doctrine.orm.entity_manager ]

    mangocele.repository.user:
            class: Doctrine\Common\Persistence\ObjectRepository
            factory_service: doctrine # this is an instance of Registry
            factory_method: getRepository
            arguments:
                - "MangoceleUserBundle:User"