parameters:
#    mangocele_user.example.class: Mangocele\UserBundle\Example

services:
#    mangocele_user.example:
#        class: %mangocele_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
