parameters:
#    mangocele_site.example.class: Mangocele\siteBundle\Example

services:
#    mangocele_site.example:
#        class: %mangocele_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
