mangocelecore:
    resource: "@MangocelecoreBundle/Resources/config/routing.yml"
    prefix:   /

MangocelecoreBundle_admin_categorias:
    resource: "@MangocelecoreBundle/Resources/config/routing/categorias.yml"
    prefix:   /admin/categorias

MangocelecoreBundle_admin_subcategorias:
    resource: "@MangocelecoreBundle/Resources/config/routing/subcategorias.yml"
    prefix:   /admin/subcategorias

MangocelecoreBundle_admin_productos:
    resource: "@MangocelecoreBundle/Resources/config/routing/productos.yml"
    prefix:   /admin/productos

mangocele_user:
    resource: "@MangoceleUserBundle/Resources/config/routing.yml"
    prefix:   /

mangocele_admin:
    resource: "@MangoceleAdminBundle/Resources/config/routing.yml"
    prefix:   /

mangocelesite:
  resource: "@MangoceleSiteBundle/Resources/config/routing.yml"
  prefix:   /

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

