parameters:
#    mangocele_admin.example.class: Mangocele\AdminBundle\Example

services:
#    mangocele_admin.example:
#        class: %mangocele_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
